# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(571, 407)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.SolveButton = QtWidgets.QPushButton(Dialog)
        self.SolveButton.setGeometry(QtCore.QRect(330, 330, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Bowlby One SC")
        font.setPointSize(22)
        self.SolveButton.setFont(font)
        self.SolveButton.setStyleSheet("background-color: rgb(10, 132, 18);")
        self.SolveButton.setFlat(False)
        self.SolveButton.setObjectName("SolveButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 290, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 BlkCn BT")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(10, 132, 18);\n"
"background-color: rgb(163, 163, 163);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.openGLWidget = QtWidgets.QOpenGLWidget(Dialog)
        self.openGLWidget.setGeometry(QtCore.QRect(330, 20, 211, 191))
        self.openGLWidget.setObjectName("openGLWidget")
        self.WebcamFrame = QtWidgets.QLabel(Dialog)
        self.WebcamFrame.setGeometry(QtCore.QRect(20, 10, 291, 201))
        self.WebcamFrame.setObjectName("WebcamFrame")
        self.CameraButton = QtWidgets.QPushButton(Dialog)
        self.CameraButton.setGeometry(QtCore.QRect(330, 250, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 BlkCn BT")
        font.setPointSize(16)
        self.CameraButton.setFont(font)
        self.CameraButton.setStyleSheet("background-color: rgb(10, 132, 18);\n" "background-color: rgb(163, 163, 163);")
        self.CameraButton.setObjectName("CameraButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SolveButton.setText(_translate("Dialog", "Solve!"))
        self.pushButton_2.setText(_translate("Dialog", "Settings"))
        self.WebcamFrame.setText(_translate("Dialog", "TextLabel"))
        self.CameraButton.setText(_translate("Dialog", "Show Camera"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
